name: FTP Auto Deploy CI

on:
  push:
    branches: [ release ]

jobs:
  web-deploy:
    name: 🎉 Deploy

    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: htdocs/
        server-dir: ${{ secrets.SERVER_DIR }}
